// <auto-generated />
using EfInheritanceDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfInheritanceDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001080745_AddTPT")]
    partial class AddTPT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EfInheritanceDemo.Models.TPH.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Employee");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EfInheritanceDemo.Models.TPT.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EfInheritanceDemo.Models.TPH.Designer", b =>
                {
                    b.HasBaseType("EfInheritanceDemo.Models.TPH.Employee");

                    b.Property<string>("DesignTool")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Designer");
                });

            modelBuilder.Entity("EfInheritanceDemo.Models.TPH.Developer", b =>
                {
                    b.HasBaseType("EfInheritanceDemo.Models.TPH.Employee");

                    b.Property<string>("ProgrammingLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Developer");
                });

            modelBuilder.Entity("EfInheritanceDemo.Models.TPH.Manager", b =>
                {
                    b.HasBaseType("EfInheritanceDemo.Models.TPH.Employee");

                    b.Property<int>("TeamSize")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Manager");
                });

            modelBuilder.Entity("EfInheritanceDemo.Models.TPT.Car", b =>
                {
                    b.HasBaseType("EfInheritanceDemo.Models.TPT.Vehicle");

                    b.Property<int>("NumberOfDoors")
                        .HasColumnType("int");

                    b.ToTable("Cars", (string)null);
                });

            modelBuilder.Entity("EfInheritanceDemo.Models.TPT.ElectricCar", b =>
                {
                    b.HasBaseType("EfInheritanceDemo.Models.TPT.Car");

                    b.Property<int>("BatteryCapacity")
                        .HasColumnType("int");

                    b.ToTable("ElectricCars", (string)null);
                });

            modelBuilder.Entity("EfInheritanceDemo.Models.TPT.Car", b =>
                {
                    b.HasOne("EfInheritanceDemo.Models.TPT.Vehicle", null)
                        .WithOne()
                        .HasForeignKey("EfInheritanceDemo.Models.TPT.Car", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EfInheritanceDemo.Models.TPT.ElectricCar", b =>
                {
                    b.HasOne("EfInheritanceDemo.Models.TPT.Car", null)
                        .WithOne()
                        .HasForeignKey("EfInheritanceDemo.Models.TPT.ElectricCar", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
